version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: MSSQL
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123@
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - app-network

  app:
    build: .
    image: castores-api
    container_name: SpringApp
    depends_on:
      - mssql
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://mssql:1433;databaseName=master;encrypt=true;trustServerCertificate=true
      - SPRING_DATASOURCE_USERNAME=SA
      - SPRING_DATASOURCE_PASSWORD=Password123@
    networks:
      - app-network

volumes:
  mssql_data:

networks:
  app-network:
    driver: bridge