spring.application.name=castoresAPI

secret.key=8dec8b5fc0088e075fc525c483fc8bbf3cdcbacf68fa0424633605436fbf5755

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=master;encrypt=true;trustServerCertificate=true
spring.datasource.username=SA
spring.datasource.password=Password123@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2016Dialect

# Habilitar la interfaz de usuario de Swagger
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

# Configuracion de la API
springdoc.api-docs.title=Ecommerce Platform API
springdoc.api-docs.description=API documentation for the Ecommerce Platform
springdoc.api-docs.version=OPENAPI_3_1